services:
  mariadb:
    image: bitnami/mariadb:latest
    container_name: chatbot_mariadb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_wordpress
      - MARIADB_PASSWORD=wordpress_password
      - MARIADB_DATABASE=bitnami_wordpress
    volumes:
      - chatbot_mariadb_data:/bitnami/mariadb
    networks:
      - chatbot_wordpress-network
    ports:
      - "3307:3306"

  wordpress:
    image: bitnami/wordpress:latest
    container_name: chatbot_wordpress
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_PASSWORD=wordpress_password
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      - WORDPRESS_DATABASE_HOST=mariadb
    ports:
      - "8090:8080"
      - "8450:8443"
    volumes:
      - ./wp_root:/bitnami/wordpress  # Local directory for WordPress code
      - chatbot_wordpress_data:/bitnami/wordpress  # Added a named volume for WordPress data
    networks:
      - chatbot_wordpress-network
    depends_on:
      - mariadb

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: chatbot_phpmyadmin
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3307
    ports:
      - "8095:80"
    depends_on:
      - mariadb
    networks:
      - chatbot_wordpress-network

volumes:
  chatbot_mariadb_data:
  chatbot_wordpress_data:

networks:
  chatbot_wordpress-network:
    driver: bridge
